export default [
  {
    ignores: [
      'node_modules/',
      'vendor/',
      'www/bootstrap/',
      'www/js/**/*.min.js',
    ],
  },
  {
    files: ['www/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2020,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        wordlist: 'readonly',
        Uint32Array: 'readonly',
        Array: 'readonly',
        Math: 'readonly',
        parseInt: 'readonly',
        XMLHttpRequest: 'readonly',
        setTimeout: 'readonly',
        localStorage: 'readonly',
        MutationObserver: 'readonly',
        NodeList: 'readonly',
        HTMLElement: 'readonly',
        fetch: 'readonly',
      },
    },
    rules: {
      'indent': ['error', 2],
      'semi': ['error', 'always'],
      'no-trailing-spaces': 'error',
      'eol-last': 'error',
      'eqeqeq': ['warn', 'smart'],
      'no-var': 'warn',
      'prefer-const': 'warn',
      'no-unused-vars': ['warn', { args: 'none' }],
      'no-undef': 'error',
      'quotes': ['error', 'single', { avoidEscape: true }],
      'comma-dangle': ['error', 'always-multiline'],
      'brace-style': ['error', '1tbs'],
      'space-before-blocks': 'error',
      'keyword-spacing': 'error',
    },
  },
];
